on:
    2   push:
    3     branches:
    4       - main
    5   workflow_dispatch:
    6
    7 jobs:
    8   build:
    9     runs-on: ubuntu-latest
   10     steps:
   11       - uses: actions/checkout@v3
   12       - uses: subosito/flutter-action@v2
   13         with:
   14           channel: 'stable'
   15       - run: |
   16           cd flutter_app
   17           flutter pub get
   18           flutter build apk --release
   19       - uses: actions/upload-artifact@v3
   20         with:
   21           name: release-apk
   22           path: flutter_app/build/app/outputs/flutter-apk/app-release.apk
